<?php
	/**
	 * Archivo principal del módulo donde están los métodos generales
	 * como los son los hooks de drupal.
	 */

	/**
	 * hook_form_alter
	 *
	 * Modificar formularios acorde lo necesario para el módulo
	 *
	 * @param $form
	 * @param $form_state
	 * @param $form_id
	 */
	function optiken_form_alter(&$form, &$form_state, $form_id) {
		$options = array('' => '- Todos -');
		switch($form['#id']) {
			case 'contact-site-form':
				$form['name']['#title'] = t('Nombre');
				$form['mail']['#title'] = t('Correo electrónico');
				$form['subject']['#title'] = t('Asunto');
				$form['message']['#title'] = t('Mensaje');
				$form['copy']['#title'] = t('Enviarme una copia');
				$form['actions']['submit']['#value'] = t('Enviar mensaje');
				drupal_add_css(drupal_get_path('module', 'optiken') . '/css/contacto.css');
				break;
			default:
				$uno = 1;
				break;
		}
	}